---
- name: a
  apt:
    name:
      - build-essential
      - apache2
      - php
      - openssl
      - perl
      - make
      - php-gd
      - libgd-dev
      - libapache2-mod-php
      - libperl-dev
      - libssl-dev
      - daemon
      - wget
      - apache2-utils
      - unzip
    state: latest
    update_cache: yes

- name: l
  group:
    name: nagios
    state: present

- name: e
  group:
    name: nagcmd
    state: present

- name: x
  user:
    name: nagios
    shell: /bin/bash
    comment: nagios user
    group: nagios
    password: alex

- name: nag
  user:
    name: nagios
    group: nagcmd
    append: yes

- name: downloads
  file:
    path: /downloads
    state: directory
    owner: nobody
    group: nogroup

- name: url
  get_url:
    url: http://prdownloads.sourceforge.net/sourceforge/nagios/nagios-4.2.1.tar.gz
    dest: /downloads

- name: nagiosplug
  get_url:
    url: https://nagios-plugins.org/download/nagios-plugins-2.3.3.tar.gz
    dest: /downloads

# tasks file for roles/install
