---
- name: commands
  unarchive:
    src: /downloads/nagios-plugins-2.3.3.tar.gz
    dest: /downloads
    remote_src: yes

- name: user
  command: ./configure --with-nagios-user=nagios --with-nagios-group=nagios
  args:
    chdir: /downloads/nagios-plugins-2.3.3

- name: plug
  make:
    chdir: ./downloads/nagios-plugins-2.3.3
  become: yes

- name: install
  make:
    target: install
    chdir: /downloads/nagios-plugins-2.3.3
  become: yes


- name: nag
  service:
    name: nagios
    state: started

# tasks file for roles/plug
